version: 2.1

jobs:
  test-backend:
    docker:
      - image: cimg/node:18.20 # Node version matching your backend
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: |
            cd back-end
            npm install
      - run:
          name: Run backend tests
          command: |
            cd back-end
            mkdir -p uploads
            npm test

  build-and-push:
    docker:
      - image: cimg/base:stable
    environment:
      DOCKER_HUB_USERNAME: yahyeapps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build backend image
          command: |
            cd back-end
            docker build -t $DOCKER_HUB_USERNAME/image-resizer-backend:latest .
      - run:
          name: Build frontend image
          command: |
            cd front-end
      - run:
          name: Push images to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            docker push $DOCKER_HUB_USERNAME/image-resizer-backend:latest
 
workflows:
  version: 2
  build-and-test:
    jobs:
      - test-backend:
          filters:
            branches:
              only: main
      - build-and-push:
          requires:
            - test-backend
          filters:
            branches:
              only: main
