version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    environment:
      DOCKER_HUB_USERNAME: yahyeapps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build backend image
          command: |
            cd back-end
            docker build -t $DOCKER_HUB_USERNAME/image-resizer-backend:latest .
      - run:
          name: Build frontend image
          command: |
            cd front-end
            docker build -t $DOCKER_HUB_USERNAME/image-resizer-frontend:latest .
      - run:
          name: Push images to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            docker push $DOCKER_HUB_USERNAME/image-resizer-backend:latest
            docker push $DOCKER_HUB_USERNAME/image-resizer-frontend:latest

workflows:
  version: 2
  build:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
